#!/usr/bin/env bash
# Installs and setup haproxy

sudo apt-get -y update
sudo apt-get install -y haproxy

echo "ENABLED=1" > /etc/default/haproxy

# Listen to web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 440660-web-01 54.86.148.149:80 check
   server 440660-web-02 100.26.247.104:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
