#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop and "Hi" in the 9th iter.

i=10

while ((i!=0))
do
  echo "Best School"
  if  ((i==2))
  then
    echo "Hi"
  fi
  ((i--))
done
